### ISSUE TITLE
Poetry install fails on Big Sur

### ISSUE THREAD

**Issue by twitzelbos** [rotkehlxen/suncal#14]
Poetry install fails on installing numpy on Big Sur
`      running install_scripts
    Traceback (most recent call last):
      File "/Users/thomaswitzel/Library/Caches/pypoetry/virtualenvs/suncal-1ZS7BLU5-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
        main()
      File "/Users/thomaswitzel/Library/Caches/pypoetry/virtualenvs/suncal-1ZS7BLU5-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/thomaswitzel/Library/Caches/pypoetry/virtualenvs/suncal-1ZS7BLU5-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 204, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
      File "/private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-build-env-v_0of4b8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 211, in build_wheel
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',
      File "/private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-build-env-v_0of4b8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 197, in _build_with_temp_dir
        self.run_setup()
      File "/private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-build-env-v_0of4b8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-build-env-v_0of4b8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 513, in <module>
        setup_package()
      File "setup.py", line 505, in setup_package
        setup(**metadata)
      File "/private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-req-build-u319hen3/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-build-env-v_0of4b8/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-build-env-v_0of4b8/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 328, in run
        impl_tag, abi_tag, plat_tag = self.get_tag()
      File "/private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-build-env-v_0of4b8/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 252, in get_tag
        plat_name = get_platform(self.bdist_dir)
      File "/private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-build-env-v_0of4b8/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 48, in get_platform
        result = calculate_macosx_platform_tag(archive_root, result)
      File "/private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-build-env-v_0of4b8/overlay/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 356, in calculate_macosx_platform_tag
        assert len(base_version) == 2
    AssertionError
    
    ########### EXT COMPILER OPTIMIZATION ###########
    Platform      :
      Architecture: x64
      Compiler    : clang
    
    CPU baseline  :
      Requested   : 'min'
      Enabled     : SSE SSE2 SSE3
      Flags       : -msse -msse2 -msse3
      Extra checks: none
    
    CPU dispatch  :
      Requested   : 'max -xop -fma4'
      Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
      Generated   :
                  :
      SSE41       : SSE SSE2 SSE3 SSSE3
      Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1
      Extra checks: none
      Detect      : SSE SSE2 SSE3 SSSE3 SSE41
                  : numpy/core/src/umath/_umath_tests.dispatch.c
                  :
      SSE42       : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT
      Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2
      Extra checks: none
      Detect      : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42
                  : build/src.macosx-11-x86_64-3.9/numpy/core/src/_simd/_simd.dispatch.c
                  :
      AVX2        : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C
      Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mavx2
      Extra checks: none
      Detect      : AVX F16C AVX2
                  : numpy/core/src/umath/_umath_tests.dispatch.c
                  :
      (FMA3 AVX2) : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C
      Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2
      Extra checks: none
      Detect      : AVX F16C FMA3 AVX2
                  : build/src.macosx-11-x86_64-3.9/numpy/core/src/_simd/_simd.dispatch.c
                  :
      AVX512F     : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2
      Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f
      Extra checks: AVX512F_REDUCE
      Detect      : AVX512F
                  : build/src.macosx-11-x86_64-3.9/numpy/core/src/_simd/_simd.dispatch.c
                  :
      AVX512_SKX  : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD
      Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq
      Extra checks: AVX512BW_MASK AVX512DQ_MASK
      Detect      : AVX512_SKX
                  : build/src.macosx-11-x86_64-3.9/numpy/core/src/_simd/_simd.dispatch.c
    CCompilerOpt._cache_write[796] : write cache to path -> /private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-req-build-u319hen3/build/temp.macosx-11-x86_64-3.9/ccompiler_opt_cache_ext.py
    
    ########### CLIB COMPILER OPTIMIZATION ###########
    Platform      :
      Architecture: x64
      Compiler    : clang
    
    CPU baseline  :
      Requested   : 'min'
      Enabled     : SSE SSE2 SSE3
      Flags       : -msse -msse2 -msse3
      Extra checks: none
    
    CPU dispatch  :
      Requested   : 'max -xop -fma4'
      Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
      Generated   : none
    CCompilerOpt._cache_write[796] : write cache to path -> /private/var/folders/d5/hszbv9mj2rg7dxrqbb0dgp540000gn/T/pip-req-build-u319hen3/build/temp.macosx-11-x86_64-3.9/ccompiler_opt_cache_clib.py
    ----------------------------------------
    ERROR: Failed building wheel for numpy
  Failed to build numpy
  ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
  

  at /usr/local/lib/python3.9/site-packages/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│ 
      1076│         return decode(output)
      1077│ 
      1078│     def execute(self, bin, *args, **kwargs):

`

**Comment by rotkehlxen** [comment]
This is a known BigSur issue, unfortunately apparently not resolved yet: https://github.com/numpy/numpy/issues/15947 There are some ugly workarounds - luckily, suncal does not depend on numpy and so this PR https://github.com/rotkehlxen/suncal/pull/15 fixed it for us.
