### ISSUE TITLE
Invalid geographical location throws unhandled exception

### ISSUE THREAD

**Issue by twitzelbos** [rotkehlxen/suncal#17]
Traceback (most recent call last):
  File "/Users/thomaswitzel/Library/Caches/pypoetry/virtualenvs/suncal-1ZS7BLU5-py3.9/lib/python3.9/site-packages/astral/sun.py", line 771, in sunrise
    return time_of_transit(
  File "/Users/thomaswitzel/Library/Caches/pypoetry/virtualenvs/suncal-1ZS7BLU5-py3.9/lib/python3.9/site-packages/astral/sun.py", line 343, in time_of_transit
    hourangle = hour_angle(
  File "/Users/thomaswitzel/Library/Caches/pypoetry/virtualenvs/suncal-1ZS7BLU5-py3.9/lib/python3.9/site-packages/astral/sun.py", line 243, in hour_angle
    HA = acos(h)
ValueError: math domain error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/thomaswitzel/projects/suncal/suncal/capi-quickstart.py", line 67, in <module>
    suncal(
  File "/Users/thomaswitzel/projects/suncal/suncal/main.py", line 90, in suncal
    events: List[GoogleCalEvent] = create_calendar_events(
  File "/Users/thomaswitzel/projects/suncal/suncal/main.py", line 45, in create_calendar_events
    sun_parameters = Celestial(
  File "/Users/thomaswitzel/projects/suncal/suncal/models/astro.py", line 32, in event
    sunrise = self.location.sunrise(date=self.date)
  File "/Users/thomaswitzel/Library/Caches/pypoetry/virtualenvs/suncal-1ZS7BLU5-py3.9/lib/python3.9/site-packages/astral/location.py", line 318, in sunrise
    return astral.sun.sunrise(observer, date, self.tzinfo)
  File "/Users/thomaswitzel/Library/Caches/pypoetry/virtualenvs/suncal-1ZS7BLU5-py3.9/lib/python3.9/site-packages/astral/sun.py", line 781, in sunrise
    raise ValueError(msg) from exc
ValueError: Sun is always below the horizon on this day, at this location.

**Comment by rotkehlxen** [comment]
These are actually two issues:
i) catching invalid values of longitude/latitude: can be caught when command line parameters are parsed 
ii) exception handling for valid geographic locations in which the sun is actually below/above the horizon so that there is no sunrise/sunset (it also affects the golden hour of course, which might just last the whole day 😸
