### ISSUE TITLE
Sometimes you get a bad pickle

### ISSUE THREAD

**Issue by twitzelbos** [rotkehlxen/suncal#48]
Seems like the token.pickle can become invalid or so and needs to be manually deleted. This might be a co-issue with

**Comment by rotkehlxen** [comment]
PS: this situation came up after un upgrade of google api client packages and might not be a general issue for someone who uses the package with a fixed version of these dependencies.

**Comment by rotkehlxen** [comment]
Can confirm now that as soon as the token has expired, we get an error that does not indicate that this is the reason - and yes, manual deletion of the token.pickle file fixes this.

So this needs to be addressed.

Error traceback:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Franzis/learning/suncal/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Franzis/learning/suncal/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/Franzis/learning/suncal/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Franzis/learning/suncal/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Franzis/learning/suncal/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Franzis/learning/suncal/suncal/suncal.py", line 129, in api
    suncal_main(
  File "/Users/Franzis/learning/suncal/suncal/suncal.py", line 77, in suncal_main
    credentials = get_credentials(SCOPES)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Franzis/learning/suncal/suncal/auth.py", line 33, in get_credentials
    creds.refresh(Request())
  File "/Users/Franzis/learning/suncal/.venv/lib/python3.11/site-packages/google/oauth2/credentials.py", line 335, in refresh
    ) = reauth.refresh_grant(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Franzis/learning/suncal/.venv/lib/python3.11/site-packages/google/oauth2/reauth.py", line 351, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/Users/Franzis/learning/suncal/.venv/lib/python3.11/site-packages/google/oauth2/_client.py", line 73, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
```
